version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-mc:
    image: minio/mc
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && \
      mc mb myminio/$MINIO_BUCKET_LANDING && \
      mc mb myminio/$MINIO_BUCKET_SPARK && \
      mc mb myminio/$MINIO_BUCKET_SPARK/spark-events && \
      mc mb myminio/$MINIO_BUCKET_SPARK/spark-libs
      "
    env_file:
      - .env

volumes:
  minio-data: